version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=ui_test
      - POSTGRES_PASSWORD=ui_test
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init-table.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: gorilla-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: gorilla-api
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ENV: prod
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ui_test
      DB_PASSWORD: ui_test
      DB_NAME: ui_test
      PORT: 8080:8080
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local